# Generated by Django 4.1.4 on 2022-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_p_phone_booking_p_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.TextField(),
        ),
    ]
